[package]
name = "mock-token"
version = "0.1.0"
authors = ["dmytro.shashkevych@megadevllc.com"]
edition = "2021"


[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.3"
near-contract-standards = "4.0.0-pre.6"
